apiVersion: skaffold/v1beta2
kind: Config 
build:
  local: 
    push: false 
  artifacts:
    - image: brianrienecker/multi-client
      context: client 
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': . 
        '**/*.cds': .
        '**/*.html': .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml